# Generated by Django 5.1.1 on 2024-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anketaApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "numberPhone",
                    models.CharField(max_length=50, verbose_name="Номер телефона"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FIO", models.CharField(max_length=50, verbose_name="ФИО")),
                ("bithDate", models.DateField(verbose_name="Дата рождения")),
                (
                    "seriesNumberLicence",
                    models.CharField(max_length=50, verbose_name="Серия и номер прав"),
                ),
                (
                    "dateOfStartDrive",
                    models.DateField(verbose_name="Дата начала стажа категории B"),
                ),
                (
                    "changeLicence",
                    models.CharField(
                        max_length=3, verbose_name="Менялись права за год?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FIO", models.CharField(max_length=50, verbose_name="ФИО")),
                ("bithDate", models.DateField(verbose_name="Дата рождения")),
                (
                    "seriesNumberPassport",
                    models.CharField(
                        max_length=50, verbose_name="Серия и номер паспорта"
                    ),
                ),
                (
                    "dateGivePassport",
                    models.DateField(verbose_name="Дата выдачи паспорта"),
                ),
                (
                    "adreesReg",
                    models.CharField(max_length=100, verbose_name="Адрес регистрации"),
                ),
                (
                    "numberAppart",
                    models.CharField(max_length=10, verbose_name="Номер крвартиры"),
                ),
                (
                    "fioCearAuto",
                    models.CharField(
                        max_length=50,
                        verbose_name="Кто страхует транспортное средство?",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="car",
            old_name="numberSTS",
            new_name="seriesNumberSTS",
        ),
    ]
