# Generated by Django 5.1.1 on 2024-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anketaApp", "0002_contacts_driver_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="dateCreate",
            field=models.CharField(max_length=4, verbose_name="Год выпуска"),
        ),
    ]
