# Generated by Django 5.1.1 on 2024-10-07 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anketaApp", "0003_alter_car_datecreate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="bithDate",
            new_name="bithDateDriver",
        ),
        migrations.RenameField(
            model_name="driver",
            old_name="FIO",
            new_name="fioDriver",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="bithDate",
            new_name="bithDateOwner",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="FIO",
            new_name="fioOwner",
        ),
    ]
