# Generated by Django 5.1.1 on 2024-10-30 11:23

import anketaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anketaApp", "0005_alter_car_numberauto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID_MARK", models.TextField()),
                ("Марка", models.TextField()),
                ("Марка_кириллица", models.TextField()),
                (
                    "Популярная_марка",
                    models.PositiveSmallIntegerField(
                        validators=[anketaApp.models.validate_popular_mark]
                    ),
                ),
                ("Страна", models.TextField()),
                ("MODEL_ID", models.TextField()),
                ("Модель", models.TextField()),
                ("Модель_кириллица", models.TextField()),
                ("Класс", models.TextField()),
                ("Год_от", models.BigIntegerField()),
                ("Год_до", models.FloatField()),
            ],
            options={
                "db_table": "cars",
            },
        ),
    ]
