# Generated by Django 5.1.1 on 2024-11-06 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anketaApp", "0006_cars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="changeLicence",
        ),
    ]
